config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#index'
  get 'sign_up', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users do
    resources :forms do
      get 'result', to: 'forms#result'
      resources :questions do
        resources :answers
      end
    end
    resources :answered_forms
  end
end

app/models/answered_form.rb
class AnsweredForm < ApplicationRecord
  belongs_to :form
  has_many :answered_questions

  accepts_nested_attributes_for :answered_questions
end

app/models/answered_question.rb
class AnsweredQuestion < ApplicationRecord
  belongs_to :question
  belongs_to :answered_form

  def same_result
    AnsweredQuestion.where(question_id: question_id, user_answer: user_answer).count
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord
  belongs_to :user
  has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :form
  has_many :answered_questions

  def answers_stat
    total = answered_questions.count
    stat = {}
    answers.each_with_index do |answer, index|
      stat[answer] = (AnsweredQuestion.where(question_id: id, user_answer: index.to_s).count.to_f * 100) / total 
    end
    stat
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :forms
  has_many :answered_forms

  def authenticate(password)
    self.password == password
  end
end

app/controllers/answered_forms_controller.rb
class AnsweredFormsController < ApplicationController
  def new
    unless current_user
      store_location
      redirect_to login_path
    end
    @form = Form.find(params[:form_id])
    @answered_form = AnsweredForm.new
    @form.questions.each do |question|
      @answered_form.answered_questions.new(question_id: question.id)
    end
  end

  def create
    answered_form = current_user.answered_forms.new(answered_form_params)
    answered_form.save
    flash[:notice] = 'You answers has been submitted'
    redirect_to user_forms_path current_user
  end

  private

  def answered_form_params
    params.require(:answered_form).permit(:form_id, answered_questions_attributes: [:user_answer, :question_id])
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :init_question

  def new
  end

  def create
    answer = params[:answer]
    question = Question.find(params[:question_id])
    question.answers.push(answer)
    question.save
    flash[:notice] = 'New answer has been added'
    redirect_to user_form_path(current_user, @form, @question)
  end

  def edit
    @index = params[:index]
  end

  def update
    question = Question.find(params[:question_id])
    question.answers[params[:answer_index].to_i] = params[:answer]
    question.save
    flash[:notice] = 'Answer has been updated'
    redirect_to user_form_path(current_user, @form, @question)
  end

  def destroy
    question = Question.find(params[:question_id])
    question.answers.delete_at params[:index].to_i
    question.save
    flash[:notice] = 'Answer has been deleted'
    redirect_to user_form_path(current_user, @form, @question)
  end

  private

  def init_question
    @form = current_user.forms.find(params[:form_id])
    @question = @form.questions.find(params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def index
    @forms = current_user.forms
  end

  def new
    @form = Form.new
  end

  def create
    form = current_user.forms.new(form_params)
    if form.save
      flash[:notice] = 'A new form has been successfully created'
      redirect_to user_forms_path
    else
      flash[:notice] = 'Can\'t not creating new form'
    end
  end

  def show
    @form = Form.find(params[:id])
  end

  def result
    @form = Form.find(params[:form_id])
  end

  def edit
    @form = Form.find(params[:id])
  end

  def update
    form = Form.find(params[:id])
    form.update(form_params)
    flash[:notice] = "#{form.title} has been updated"
    redirect_to user_form_path(current_user, params[:id])
  end

  def destroy
    form = Form.find(params[:id])
    form.delete
    flash[:notice] = "#{form.title} has been deleted"
    redirect_to user_form_path(current_user, params[:id])
  end

  private

  def form_params
    params.require(:form).permit(:title, :description)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :init_form

  def new
    @question = @form.questions.new
  end

  def edit
    @question = @form.questions.find_by(id: params[:id])
  end

  def create
    question = @form.questions.new(question_params)
    question.save
    flash[:notice] = ' A new question has been created'
    redirect_to user_form_path(current_user, params[:form_id])
  end

  def update
    question = Question.find(params[:id])
    return unless question.update(question_params)

    flash[:notice] = 'Question has been updated'
    redirect_to user_form_path(current_user, params[:form_id])
  end

  def destroy
    question = Question.find(params[:id])
    return unless question.destroy

    flash[:notice] = 'Question has been deleted'
    redirect_to user_form_path(current_user, params[:form_id])
  end

  def show
    @question = @form.question.find(params[:id])
  end

  private

  def question_params
    params.require(:question).permit(:question_text, :question_type, :form_id)
  end

  def init_form
    @form = current_user.forms.find(params[:form_id])
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    redirect_to user_forms_path current_user and return if current_user
      
    redirect_to login_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    session = params[:session]
    user = User.find_by(email: session[:email])
    if user && user.authenticate(session[:password])
      login user
      flash[:notice] = "Hello #{user.email} !!!"
      if session[:return_to]
        redirect_to session[:return_to]
      else
        redirect_to user_forms_path current_user
      end
    else
      flash[:notice] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:notice] = 'You has been logged out'
    redirect_to login_path
  end
end

app/controllers/static_controller.rb
class StaticController < ActionController::Base
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    User.create(user_params)
    flash[:notice] = 'Account create successful'
    redirect_to login_path
  end

  def update
  end

  def show
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find session[:user_id]
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def store_location
    session[:return_to] = request.path
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/answered_forms/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 bg-light">
    </div>
    <div class="col-md-6">
      <br>
      <h3 class="text-center"><%= @form.title%></h3>
      <hr>
      <p class="text-left"><%= @form.description%></p>
      <hr>
      <%= form_for @answered_form, url: user_answered_forms_path do |f| %>
        <%= f.hidden_field :form_id, value: @form.id %>
        <br>
        <ol class="list-group">
        <%= f.fields_for :answered_questions do |ans| %>
          <%= ans.hidden_field :question_id, value: @form.questions[ans.index].id %>
            <li class="list-group-item">
            <p><%= @form.questions[ans.index].question_text %></p>
              <% if @form.questions[ans.index].question_type == "Multiple choice" %>
                <% @form.questions[ans.index].answers.each_with_index do |answer, index| %>
                  <div class="form-group">
                    <%= ans.radio_button :user_answer, index %>
                    <%= label :user_answer, answer %>
                  </div>
                <% end %>
              <% else %>
                <div class="form-group">
                  <%= ans.text_field :user_answer, placeholder: 'Type your answer here', class:'form-control'%>
                </div>
              <% end %>
            </li>
        <% end %>
        </ol>
        <%= f.submit 'Submit answer', class: 'btn btn-success w-100'%>
      <% end %>
    </div>
    <div class='col-md-3 bg-light'>
    </div>
  </div>
</div>

app/views/answers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <br>      
      <h1> Update answer</h1>
      <%= form_tag(user_form_question_answer_path(answer_index: @index), method: 'put') do %>
        <div class="form-group">
          <%= label_tag(:answer, 'Answer')%>
          <%= text_field_tag(:answer, '', class: 'form-control')%>
        </div>
        <%= submit_tag("Update answer", class: 'btn btn-success w-100') %>
      <% end %>
    </div>
  </div>
</div>           

app/views/answers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <br>    
      <h1> Add new answer </h1>
      <%= form_tag(user_form_question_answers_path, method: 'post') do %>
        <div class="form-group">
          <%= label_tag(:answer, 'Answer')%>
          <%= text_field_tag(:answer, "" ,class: 'form-control')%>
        </div>
        <%= submit_tag("Create answer", class: 'btn btn-success w-100') %>
      <% end %>
    </div>
  </div>
</div>      

app/views/forms/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <br>  
      <h1> Edit form</h1>
      <%= form_for @form, url:  user_form_path() do |f| %>
        <div class="form-group">
          <%= f.label :title, 'Title: ' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">  
          <%= f.label :description, 'Description: ' %>
          <%= f.text_field :description, class: 'form-control'%>
        </div>
        <div class="btn-group w-100">
        <%= f.submit 'Update', class: 'btn btn-success' %>
        <%= link_to 'Cancel',user_forms_url, class: 'btn btn-danger'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/forms/index.html.erb
<div class="container-fluid">
  <div class="row">
    <% @forms.each do |form|%>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title"><%= form.title%></h4>
          </div>
          <div class="card-body">
            <p class="card-text" ><%= form.description %></p>
            <%= link_to 'View Form', user_form_path(current_user, form.id), class: 'btn btn-primary'%>
            <%= link_to 'Edit', edit_user_form_path(current_user, form.id), class: 'btn btn-primary'%>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/forms/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <br>  
      <h1> Create a new form</h1>
      <%= form_for @form, url: user_forms_path() do |f| %>
        <div class="form-group">
          <%= f.label :title, 'Title: ' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">  
          <%= f.label :description, 'Description: ' %>
          <%= f.text_field :description, class: 'form-control'%>
        </div>
        <div class="btn-group w-100">
        <%= f.submit 'Create', class: 'btn btn-success' %>
        <%= link_to 'Cancel',user_forms_url, class: 'btn btn-danger'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/forms/result.html.erb
<div class="row">
  <div class="col-md-3 bg-light">
  </div>
  <div class="col-md-6">
    <h3 class="text-center"><%= @form.title%></h3>
    <hr>
    <p class="text-left"><%= @form.description%></p>
    <hr>
    <ol class="list-group">
    <% @form.questions.each do |question| %>
      <li class="list-group-item bg-light">
      <p><%= question.question_text %></p>
        <% if question.question_type == 'Multiple choice'%>
          <% question.answers.each_with_index do |answer, index| %>
            <hr>
            <p><%= "#{answer}: " %></p>
            <div class="progress">
              <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:<%= question.answers_stat[answer].round %>%">
                <%= question.answers_stat[answer].round %> %
              </div>
            </div>
            <br>
          <% end %>
        <% else %>
          <ul class="list-group">
            <% question.answered_questions.each do |answer| %>
              <li class="list-group-item"><%= answer.user_answer %></li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
      </li>
    </ol>
    <br>
    <div class="alert alert-info">
      <strong>Share this form by copy this </strong> <%= link_to 'Link', new_user_answered_form_url(form_id: @form.id), class: 'alert-link' %>
    </div>
  </div>
  <div class='col-md-3 bg-light'>
  </div>
</div>

app/views/forms/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6 bg-light">
      <br>
      <h3 class="text-center"><%= @form.title%></h3>
      <hr>
      <p class="text-left"><%= @form.description%></p>
      <hr>
      <% unless @form.questions.empty?%>
        <ol class="list-group">
          <% @form.questions.each do |question| %>
            <li class="list-group-item">
              <p><%= question.question_text %></p>
              <span>
              <%= link_to 'Edit', edit_user_form_question_path(current_user, @form,question) %>
              <%= link_to 'Delete', user_form_question_path(current_user, @form, question), method: :delete, data: {confirm: 'Are you sure ?'} %>
              <% if question.question_type == 'Multiple choice'%>
                <%= link_to 'New Answer', new_user_form_question_answer_path(current_user, @form, question)%>
              <% end%>
              </span>
              <% unless question.answers.empty?%>
              <ul class="list-group list-group-flush">
                <% question.answers.each_with_index do |answer, index| %>
                  <li class="list-group-item text-dark">
                    <input type="radio" class="form-check-input" name="optradio">
                    <%= answer %>
                    <%= link_to 'Edit', edit_user_form_question_answer_path(current_user, @form, question, index: index)%>
                    <%= link_to 'Delete', user_form_question_answer_path(current_user, @form, question, index: index), method: :delete%>
                  </li>
                <% end %>
              </ul>
              <% end %>
            </li>
          <% end %>
        </ol>
      <% end%>
      <br>
      <div class="btn-group w-100">
        <%= link_to 'Add new question', new_user_form_question_url(current_user, @form.id), class: 'btn btn-success' %>
        <br>
        <%= link_to 'Delete this form', user_form_url(current_user, @form.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'%>
        <br>
        <%= link_to 'Return to list',user_forms_url, class: 'btn btn-primary'%>
        <br>
        <%= link_to 'View Stat', user_form_result_path(form_id: @form.id), class:'pull-left btn btn-info'%>
      </div>
      <div class="alert alert-info">
        <strong>You can share this form via this </strong> <%= link_to 'Link', new_user_answered_form_url(form_id: @form.id), class: 'alert-link' %>
      </div>
    </div>
    <div class='col-md-3'>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <%= link_to 'Form Manager', root_path, class: 'navbar-brand' %>
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item">
            <%=link_to 'Create new form', new_user_form_url(current_user), class: 'nav-link'%>
          </li>        
          <li class="nav-item">
            <%= link_to 'Logout', logout_url, method: :delete, class: 'nav-link'%>
          </li>
        <% else %>
            <%= link_to 'Sign up', sign_up_path, class: 'nav-link'%>
        <% end %>
      </ul>
    </nav>
    <% flash.each do |key, value| %>
      <div id="error_explanation">
        <div class="alert alert-#{key}">
          <%= value unless value.blank? %>
        </div>
      </div>
    <% end %>    
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <br>       
      <h3>Edit Question</h3>
      <%= form_for(@question, url: user_form_question_path) do |f| %>
        <div class="form-group">
          <%= f.label :question_text %>
          <%= f.text_field :question_text, class: 'form-control' %>
        </div>
        <%= f.submit 'Update', class: 'btn btn-success w-100'%>
      <% end %> 
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<h3><%= @form.title %></h3>
<h4> Questions list <%= link_to 'New Question', new_user_form_question_path(current_user, @form)%></h4>
<ol>
  <% @questions.each do |q| %>
    <li><b><%= q.question_text %></b></li>
  <% end %>
</ol>

app/views/questions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <br>       
      <h3>New Question</h3>
      <%= form_for @question,url: user_form_questions_path(current_user, @form, @question) do |f| %>
        <div class="form-group">
          <%= f.label :question_text %>
          <%= f.text_field :question_text, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :question_type %>
          <%= f.select :question_type, class: 'form-control' do  %>
            <% ['Multiple choice', 'Short answer'].each do |c| %>
              <%= content_tag(:option, c) %>
            <% end %>
          <% end %>
        </div>
        <%= f.submit 'Create', class: 'btn btn-success w-100' %>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
  <% flash.each do |key, value| %>
    <div id="error_explanation">
      <div class="alert alert-#{key}">
        <%= value unless value.blank? %>
      </div>
    </div>
  <% end %>
  <h3>Question Text:</h3>
  <%= @question.question_text%>
  <h3>Type</h3>
  <%= @question.question_type%>
  <h3> Answers </h3>
  <ul>
    <% unless @question.answers.nil?%>
      <% @question.answers.each do |answer|%>
        <li> answer </li>
      <% end %>
    <% end %>
  </ul>
  <br>
  <div>
    <%= link_to 'Delete this question', form_question_url(@question.id), method: :delete, data: {confirm: 'Are you sure?'}%>
    <br>
    <%= link_to 'Return to list',form_questions_url%>
  </div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      <br>
      <h1> Sign up </h1>
      <%= form_for(@user) do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control'%>
        </div>
        <%= f.submit 'Create' , class: 'btn btn-success w-100'%>
      <% end %>
    </div>
    <div class="col-md-2">
    </div>        
  </div>
</div>